### PR TITLE
Add rule to disallow removal of the admin bar.

### LINKED ISSUE #1: [New sniff] No disabling of the admin toolbar.
#### Rule:

No hiding of the admin bar - check if `show_admin_bar( false )` is called or if `add_filter( 'show_admin_bar', '__return_false' )` is somewhere in the code. 

Ref: https://make.wordpress.org/themes/handbook/review/required/#core-functionality-and-features
#### Theme check file covering this rule:

https://github.com/Otto42/theme-check/blob/master/checks/adminbar.php
#### To do:

~~\- [ ] Create unit tests~~
~~\- [ ] Create new sniff~~
- [ ] Open PR upstream in WPCS to improve the admin bar removal sniff.
- [ ] Add `WordPress_Sniffs_VIP_AdminBarRemovalSniff` sniff to the ruleset.

### PR DESCRIPTION
**Pull request by grappler**
fixes #1

### CODE REVIEW

**Comment by fklein-lu** [comment]
Is there more information about the upstream change that we are waiting for?

**Comment by grappler** [comment]
Sorry, yes. The [current Sniff](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/blob/develop/WordPress/Sniffs/VIP/AdminBarRemovalSniff.php) does not cover all of the use cases.

The ways that we found are `add_filter('show_admin_bar', '__return_false');`, `show_admin_bar(false)` and `#wpadminbar{display:none;}`

**Comment by jrfnl** [comment]
FYI: The upstream PR which added additional checks has been merged: https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/pull/817
So, once upstream has been merged back into this repo, you'll get the full benefits of it. In the mean time, this PR could be merged already.

I would recommend adding the new `remove_only` property to the ruleset though as it was specifically added for TRTCS.

```xml
<rule ref="WordPress.VIP.AdminBarRemoval">
	<properties>
		<property name="remove_only" value="false" />
	</properties>
</rule>
```

**Comment by grappler** [comment]
@jrfnl I have updated the PR but I just understood the meaning of the parameter `remove_only`. I am sorry but I don't think we need that parameter. We want to stop people from hiding the admin bar but we need to allow them to use the CSS ID to style their content. An example would be if you had a sticky header menu. So that half of it is not hidden under the admin bar you would add extra margin to the top. For this the admin bar ID would be needed. I hope that makes sense.

**Comment by jrfnl** [comment]
@grappler 

> I am sorry but I don't think we need that parameter.

To quote @justintadlock in https://github.com/WPTRT/WordPress-Coding-Standards/issues/1#issuecomment-233203183

> > Force-showing is as equally bad as force hiding it. Whether to show/hide the admin bar is outside the scope of themes. This is core and plugin territory.

Based on that, you would need the property.

To clarify what the property does: by default the sniff check for manipulation of the visibility of the admin bar and will flag is the admin bar is being hidden.

With the property set to `false`, it will also flag the admin bar being (force) shown.

> We want to stop people from hiding the admin bar but we need to allow them to use the CSS ID to style their content.

The sniff only checks for manipulation of certain CSS properties for selectors, `visibility`, `display` and `opacity`. Manipulation of other properties will not be flagged.

**Comment by jrfnl** [comment]
@grappler One more remark - you may want to switch out the link to one in the new handbook instead of referring to the old Theme check plugin

**Pull request merged**
